name: Build iOS IPA

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Clean build
      run: flutter clean

    - name: Configure iOS for unsigned build
      run: |
        # Remove code signing requirements
        sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/' ios/Runner.xcodeproj/project.pbxproj
        sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/' ios/Runner.xcodeproj/project.pbxproj
        sed -i '' 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "";/' ios/Runner.xcodeproj/project.pbxproj

    - name: Build iOS (without signing)
      run: |
        flutter build ios --release --no-codesign

    - name: Create IPA directory
      run: mkdir -p build/ios/ipa

    - name: Copy app to IPA structure
      run: |
        cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/

    - name: Create IPA file
      run: |
        cd build/ios/ipa
        zip -r ../../../BlockLifts.ipa Payload/

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: BlockLifts-iOS
        path: BlockLifts.ipa
        retention-days: 30